site:
  title: Ruby Introduction
  url: https://wintermeyer-consulting.de/ruby
  start_page: book::index.adoc
content:
  sources:
  - url: https://github.com/wintermeyer/ruby-book.git
    branches: main
ui:
  bundle:
    url: https://github.com/wintermeyer/wincon-antora-ui/releases/download/latest/ui-bundle.zip
    snapshot: true
  supplemental_files: ./ui-supplemental
  output_dir: antora-assets
output:
  dir: build/site
runtime:
  fetch: true
